import React, { useState, useEffect } from 'react';
import { 
  Search, 
  MessageSquare, 
  LayoutDashboard, 
  BookOpen, 
  PenTool, 
  Newspaper, 
  HelpCircle, 
  Globe, 
  ChevronRight, 
  CheckCircle2, 
  ArrowRight,
  User,
  Zap,
  TrendingUp,
  Mail,
  FileText,
  Star,
  Download,
  Copy,
  Plus,
  ArrowLeft,
  Settings,
  Menu,
  X,
  Database,
  Target
} from 'lucide-react';
import './UPSCPlatform.css';

const LogoIcon = ({ className }) => (
  <svg viewBox="0 0 24 24" className={className} fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect x="7" y="2" width="10" height="10" rx="1" transform="rotate(45 12 7)" fill="#800000" />
    <rect x="7" y="9" width="10" height="10" rx="1" transform="rotate(45 12 14)" fill="#F97316" />
  </svg>
);

const UPSCPlatform = () => {
  const [view, setView] = useState('landing');
  const [language, setLanguage] = useState('English');
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [activeChatFilter, setActiveChatFilter] = useState('Polity');
  const [searchQuery, setSearchQuery] = useState('');

  // Auto-scroll to top on view change
  useEffect(() => {
    window.scrollTo(0, 0);
  }, [view]);

  const renderLanding = () => (
    <div className="landing-view animate-slide-up">
      <section className="landing-hero">
        <span className="hero-tag">AI-Powered Preparation</span>
        <h1 style={{ fontSize: '5rem', fontWeight: '800' }}>UPSC <span style={{ color: '#F97316', fontStyle: 'italic', fontWeight: '400' }}>AI</span></h1>
        <p className="subtitle" style={{ fontSize: '1.5rem', fontWeight: '600', color: 'var(--primary-dark)', marginTop: '-10px' }}>Get 360° Analysis of Any UPSC Topic</p>
        
        <div className="hero-search-area">
          <div className="search-input-wrapper">
            <input 
              type="text" 
              placeholder="Ask anything about UPSC in seconds..." 
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              onKeyPress={(e) => e.key === 'Enter' && setView('chat')}
            />
            <button className="btn-search" onClick={() => setView('chat')}>
              <Search size={22} />
            </button>
          </div>
          <div className="query-chips">
            {['Explain Preamble', 'Article 370', 'Budget 2024'].map(chip => (
              <button key={chip} className="chip" onClick={() => {setSearchQuery(chip); setView('chat')}}>
                {chip}
              </button>
            ))}
          </div>
        </div>
      </section>

      <section className="section-feature">
        <h2>6 powerful AI tools for UPSC aspirants</h2>
        <div className="feature-grid">
          {[
            { id: 1, title: 'Doubt Resolution', desc: 'Instant clarity from 10,000+ verified UPSC sources.', icon: <HelpCircle /> },
            { id: 3, title: 'Adaptive Learning', desc: '25,000+ Prelims questions with personalized progress tracking.', icon: <TrendingUp /> },
            { id: 4, title: 'Current Affairs', desc: 'Analyzed news from 15+ premium sources specifically for UPSC.', icon: <Newspaper /> },
            { id: 6, title: 'Mains Guidance', desc: 'Expert structure, content, and presentation tips generated by AI.', icon: <PenTool /> },
          ].map((feature, i) => (
            <div key={feature.id} className={`feature-card stagger-${(i%3)+1}`}>
              <div className="icon-box">{feature.icon}</div>
              <h3>{feature.title}</h3>
              <p>{feature.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="stats-bar">
        <h3>Join 3,500+ successful candidates</h3>
        <div className="stats-grid">
          <div className="stat-item">
            <h4>1M+</h4>
            <p>MCQs Attempted</p>
          </div>
          <div className="stat-item">
            <h4>50K+</h4>
            <p>Tests Completed</p>
          </div>
          <div className="stat-item">
            <h4>250K+</h4>
            <p>Questions Answered</p>
          </div>
        </div>
      </section>

      <section className="stats-bar" style={{ background: '#FFFBF5', color: 'var(--text-dark)', borderTop: '1px solid var(--border-light)' }}>
        <div style={{ padding: '80px 20px', maxWidth: '800px', margin: '0 auto' }}>
          <h2 style={{ fontSize: '3rem', fontWeight: '800', marginBottom: '24px' }}>Start your <span style={{ color: 'var(--primary-light)' }}>AI-powered</span> UPSC journey</h2>
          <p className="subtitle" style={{ marginBottom: '40px' }}>Join 3,500+ aspirants who are already using UPSC AI to master their preparation.</p>
          <div style={{ display: 'flex', gap: '16px', justifyContent: 'center' }}>
            <button className="btn-search" style={{ padding: '16px 48px', fontSize: '1.1rem' }} onClick={() => setView('chat')}>
              Try UPSC AI for Free
            </button>
          </div>
          <div style={{ marginTop: '40px', opacity: 0.6, fontSize: '0.9rem' }}>
            Trusted by aspirants from top institutes like Vajiram, Vision, and NextIAS.
          </div>
        </div>
      </section>

      <footer style={{ padding: '40px', background: 'white', borderTop: '1px solid var(--border-light)', textAlign: 'center' }}>
         <div className="brand-group" style={{ justifyContent: 'center', marginBottom: '16px' }}>
            <LogoIcon className="w-6 h-6" />
            <span>UPSC <span style={{ color: '#F97316', fontStyle: 'italic' }}>AI</span></span>
         </div>
         <p className="text-muted" style={{ fontSize: '0.8rem' }}>© 2024 UPSC AI. Made with ❤️ for UPSC Aspirants.</p>
      </footer>
    </div>
  );

  const renderAIChat = () => (
    <div className="chat-page animate-slide-up">
      <div className="chat-room">
        <div className="chat-filters">
          {['Polity', 'History', 'Economy', 'Current Affairs', 'Environment'].map(filter => (
            <button 
              key={filter} 
              className={`filter-pill ${activeChatFilter === filter ? 'active' : ''}`}
              onClick={() => setActiveChatFilter(filter)}
            >
              {filter}
            </button>
          ))}
        </div>
        <div className="messages-area">
          <div className="msg msg-user">Explain the impact of the 73rd Amendment on PRIs in India.</div>
          <div className="msg msg-ai shadow-sm" style={{ background: 'white' }}>
            <div className="ai-card-content">
              <div className="card-title">📖 360° Analysis: 73rd Constitutional Amendment Act</div>
              
              <div className="ai-section">
                <strong>1️⃣ Introduction (150 words)</strong>
                <p>The 73rd Amendment Act, 1992, is a landmark legislation that institutionalized local self-government in India. It granted constitutional status to Panchayati Raj Institutions (PRIs), moving away from the directive principles stage to a mandatory administrative reality.</p>
              </div>

              <div className="ai-insight">
                <strong>⚖️ Key Constitutional Judgments:</strong>
                <ul>
                  <li><strong>L. Chandrakumar Case:</strong> Reaffirmed the importance of democratic decentralization.</li>
                  <li><strong>Nabam Rebia Case:</strong> Clarified the scope of discretionary powers in federal structures.</li>
                </ul>
              </div>

              <div className="ai-section">
                <strong>📝 Structured Answer for Mains:</strong>
                <ul>
                  <li><strong>Political Impact:</strong> Mandated direct elections, ensuring representation for SC, ST, and Women.</li>
                  <li><strong>Administrative Impact:</strong> Devolution of 29 subjects under the 11th Schedule.</li>
                  <li><strong>Financial Impact:</strong> Mandatory setting up of State Finance Commissions.</li>
                </ul>
              </div>

              <div className="ai-actions">
                <button className="btn-ai-action">Get Detailed Explanation (500 words)</button>
                <button className="btn-ai-action">Simplify for Prelims</button>
                <button className="btn-ai-action">Generate Mind-Map</button>
              </div>
            </div>
          </div>
        </div>
        <div className="hero-search-area" style={{ padding: '20px', background: 'var(--bg-app)', borderTop: '1px solid var(--border-light)' }}>
          <div className="search-input-wrapper" style={{ margin: 0, border: '2px solid var(--primary-light)' }}>
            <input type="text" placeholder="Explain the Preamble of Indian Constitution..." style={{ background: 'transparent' }} />
            <button className="btn-search" style={{ borderRadius: '8px', padding: '10px 16px' }}>ASK MENTOR</button>
          </div>
        </div>
      </div>
    </div>
  );

  const renderDashboard = () => (
    <div className="dashboard-grid animate-slide-up">
      <div>
        <div className="user-hero-card shadow-lg">
          <div className="avatar-large">AM</div>
          <div>
            <h2>Arjun Mehra</h2>
            <p>Target: UPSC-CSE 2025 | Consistency: 12 Days 🔥</p>
          </div>
          <div className="progress-circle ml-auto" style={{ background: 'rgba(255,255,255,0.2)' }}>
            <span>62%</span>
            <small style={{ fontSize: '0.6rem' }}>Syllabus</small>
          </div>
        </div>

        <div className="study-plan-card shadow-sm">
          <h3>Your Weekly Study Plan (Oct 18 - Oct 25)</h3>
          <div className="plan-item">
            <CheckCircle2 className="text-accent-green" />
            <div>
               <div style={{ fontWeight: '600' }}>Indian Polity - Fundamental Rights</div>
               <small className="text-muted">Target: Revise Articles 12-35 and solved 20 MCQs.</small>
            </div>
          </div>
          <div className="plan-item">
            <div style={{ width: '24px', height: '24px', borderRadius: '50%', border: '2px solid var(--border-light)' }}></div>
            <div>
               <div style={{ fontWeight: '600' }}>Geography - Physiography of India</div>
               <small className="text-muted">Schedule: 2:00 PM - 5:00 PM Today.</small>
            </div>
          </div>
          <div style={{ textAlign: 'right', marginTop: '16px' }}>
            <button className="btn-ai-action">Regenerate Study Plan</button>
          </div>
        </div>
      </div>

      <div>
        <h3>Subject Overview</h3>
        {[
          { name: 'Polity', progress: 85, suggestion: 'Focus on recent SC judgments for GS2.' },
          { name: 'Economy', progress: 42, suggestion: 'Review Banking & Inflation concepts.' },
          { name: 'History', progress: 60, suggestion: 'Revise Socio-Religious movements.' }
        ].map(sub => (
          <div key={sub.name} className="subject-card shadow-sm">
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
              <strong>{sub.name}</strong>
              <small>{sub.progress}%</small>
            </div>
            <div style={{ height: '6px', background: '#f1f5f9', borderRadius: '3px' }}>
              <div style={{ height: '100%', width: `${sub.progress}%`, background: 'var(--primary)', borderRadius: '3px' }}></div>
            </div>
            <div className="ai-insight">{sub.icon} AI Tip: {sub.suggestion}</div>
          </div>
        ))}
      </div>
    </div>
  );



  const renderCurrentAffairs = () => (
    <div className="dashboard-grid animate-slide-up" style={{ gridTemplateColumns: '1fr' }}>
       <div style={{ maxWidth: '800px', margin: '0 auto', width: '100%' }}>
         <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '32px' }}>
            <h1>Current Affairs: Oct 18, 2024</h1>
            <div className="chip">English / Hindi Toggle</div>
         </div>
         {[
           { title: 'Global Innovation Index 2024: India Ranks 39th', tag: 'High', area: 'Economy/S&T' },
           { title: 'Supreme Court ruling on Right to Privacy vs National Security', tag: 'High', area: 'Polity/GS2' },
           { title: 'New Biodiversity Mission launched by Environment Ministry', tag: 'Medium', area: 'Environment' },
         ].map(news => (
           <div key={news.title} className="study-plan-card shadow-sm mb-4" style={{ marginBottom: '16px' }}>
              <div style={{ display: 'flex', gap: '12px', marginBottom: '8px' }}>
                <span className="tag" style={{ background: news.tag === 'High' ? 'rgba(245, 158, 11, 0.1)' : 'rgba(16, 185, 129, 0.1)', color: news.tag === 'High' ? 'var(--accent-orange)' : 'var(--accent-green)' }}>
                  {news.tag} Relevance
                </span>
                <span className="tag">{news.area}</span>
              </div>
              <h3 style={{ marginBottom: '12px' }}>{news.title}</h3>
              <p className="text-muted" style={{ fontSize: '0.9rem' }}>
                AI Summary: The index highlights India's growing innovation ecosystem. Key performers include the Pharmaceutical and ICT sectors. Challenges remain in R&D investment levels.
              </p>
              <div className="ai-insight">Why this matters: Critical for GS3 Science and Technology section. Link with National Research Foundation.</div>
           </div>
         ))}
       </div>
    </div>
  );

  return (
    <div className="platform-wrapper">
      <div className="main-container">
        <header className="platform-header">
          <div className="brand-group" onClick={() => setView('landing')}>
            <Target className="text-primary" />
            <span>UPSC <span className="text-primary-light">AI</span></span>
          </div>
          
          <nav className="nav-links">
            <button className={`nav-item ${view === 'chat' ? 'active' : ''}`} onClick={() => setView('chat')}>AI Chat</button>
            <button className={`nav-item ${view === 'dashboard' ? 'active' : ''}`} onClick={() => setView('dashboard')}>Dashboard</button>
            <button className={`nav-item ${view === 'practice' ? 'active' : ''}`} onClick={() => setView('practice')}>Practice</button>
            <button className={`nav-item ${view === 'news' ? 'active' : ''}`} onClick={() => setView('news')}>Current Affairs</button>
          </nav>

          <div style={{ display: 'flex', gap: '16px', alignItems: 'center' }}>
            <div className="chip" onClick={() => setLanguage(l => l === 'English' ? 'Hindi' : 'English')}>
              {language}
            </div>
            <button className="btn-search" style={{ background: 'var(--bg-app)', color: 'var(--text-dark)', border: '1px solid var(--border-light)' }}>
              <User size={18} />
            </button>
          </div>
        </header>

        <main>
          {view === 'landing' && renderLanding()}
          {view === 'chat' && renderAIChat()}
          {view === 'dashboard' && renderDashboard()}
          {view === 'practice' && <div className="dashboard-grid animate-slide-up"><h2>Adaptive Practice: 25k+ MCQs</h2><h3 className="text-muted">Module Coming Soon...</h3></div>}
          {view === 'news' && renderCurrentAffairs()}
          {view === 'support' && <div className="landing-hero"><h1>Expert Support</h1><p className="subtitle">Coming Soon...</p></div>}
        </main>
      </div>
    </div>
  );
};

export default UPSCPlatform;
